l21-task
paxagi/Activities pull request #15
Opened 2024-02-25 22:30 UTC by paxagi

Используя прошлое приложение, добавить на ActivityB экран список предметов, интересных вам. (футболисты, машины, цветы и тд)

2024-02-26 00:01 UTC, McAndyLarkin commented on app/src/main/java/com/example/activities/InterestsAdapter.kt
> +    override fun onBindViewHolder(holder: InterestsViewHolder, position: Int) {
Боюсь, что тут принципиальное недопонимание смысла вьюХолдера. Мы уделим этому время на ближайшем синке, а пока советую самостоятельно поразбираться.

2024-02-26 00:02 UTC, McAndyLarkin requested changes
Боюсь, что тут принципиальное недопонимание смысла вьюХолдера. Мы уделим этому время на ближайшем синке, а пока советую самостоятельно поразбираться.

2024-02-26 00:11 UTC, McAndyLarkin commented
ВьюХолдер должен ссылки на результаты findViewbyid чтобы при переиспользовании холдеров экономились ресурсы системы.

2024-02-26 16:17 UTC, McAndyLarkin commented on app/src/main/java/com/example/activities/InterestsAdapter.kt
> +    inner class InterestsViewHolder(itemView: View) : RecyclerView.ViewHolder(itemView)
inner class вяно тут лишний

2024-02-26 16:20 UTC, McAndyLarkin commented on app/src/main/java/com/example/activities/InterestsAdapter.kt
> +    inner class InterestsViewHolder(itemView: View) : RecyclerView.ViewHolder(itemView)
class InterestsViewHolder(itemView: View) : RecyclerView.ViewHolder(itemView) {
val title: TextView = itemView.findViewById(R.id...)
val logo: ImageView = itemView.findViewById(R.id...)
}

2024-02-26 16:26 UTC, McAndyLarkin commented on app/src/main/java/com/example/activities/InterestsAdapter.kt
> +        holder.itemView.apply {
holder. title = interests[position].title
holder. logo.setImageResource(interests[position].image)

2024-02-26 16:26 UTC, McAndyLarkin commented on app/src/main/java/com/example/activities/InterestsAdapter.kt
> +    private lateinit var tvTitle: TextView
Это не надо

2024-02-28 09:44 UTC, McAndyLarkin commented
Ну кажется теперь очень похоже на правду

2024-02-28 09:44 UTC, McAndyLarkin approved these changes

2024-02-28 19:51 UTC, paxagi commented
https://github.com/paxagi/Activities/assets/22299289/15c1071e-ec21-4a15-b823-0e7b96c1669c

2024-02-29 19:59 UTC, MisKuchum approved these changes

2024-03-02 18:34 UTC, merged