task: add/ref: add listener and logging to button, add strings resources
paxagi/Activities pull request #2
Opened 2024-02-03 21:34 UTC by paxagi

task of lesson 7 Button

2024-02-03 22:03 UTC, firstmobileacademy requested changes

2024-02-03 22:03 UTC, firstmobileacademy commented on app/src/main/java/com/example/activities/ActivityA.kt
> +        findViewById<Button>(R.id.btn_apply).setOnClickListener {
Давай сразу будем выносить это в методы инициализации, чтобы не писать все внутри одного метода жизненного цикла

2024-02-04 11:53 UTC, paxagi commented on app/src/main/java/com/example/activities/ActivityA.kt
> +        findViewById<Button>(R.id.btn_apply).setOnClickListener {
слушатель не устанавливается в init-блоке класса, вылетает ошибка Unable to instantiate activity ComponentInfo. В чем может быть проблема?

2024-02-04 11:53 UTC, McAndyLarkin commented on app/src/main/java/com/example/activities/ActivityA.kt
> +            val name = findViewById<EditText>(R.id.first_name).text.toString()
> Привет, слушатель не устанавливается в инит-блоке класса, вылетает ошибка Unable to instantiate activity ComponentInfo. Больше получаса не могу ошибку устранить, в чем может быть проблема? 

от Артема

2024-02-04 11:53 UTC, McAndyLarkin commented on app/src/main/java/com/example/activities/ActivityA.kt
> +        findViewById<Button>(R.id.btn_apply).setOnClickListener {
> Привет, слушатель не устанавливается в инит-блоке класса, вылетает ошибка Unable to instantiate activity ComponentInfo. Больше получаса не могу ошибку устранить, в чем может быть проблема?

от Артема

2024-02-04 17:35 UTC, McAndyLarkin commented on app/src/main/java/com/example/activities/ActivityB.kt
> +                findViewById<EditText>(R.id.editTextTextB).setText(it)
Везде, где ты думаешь, что в течение работы приложения строчка с findViewById может вызваться раньше, лучше выносить это в переменную (можно ленивую, можно в onCreate создать переменную, а потом использовать в других местах)

2024-02-04 17:35 UTC, McAndyLarkin commented on app/src/main/java/com/example/activities/ActivityB.kt
> +                findViewById<EditText>(R.id.editTextTextB).setText(it)
Эта операция довольно дорогая и лучше минимизировать ее исполнение, сохраняя предыдущий результат

2024-02-05 17:25 UTC, paxagi commented on app/src/main/java/com/example/activities/ActivityB.kt
> +                findViewById<EditText>(R.id.editTextTextB).setText(it)
Дорогая операция по поиску элемента или setText ?

2024-02-06 18:57 UTC, McAndyLarkin commented on app/src/main/res/layout/activity_main.xml
> +            android:id="@+id/first_name"
minor: id в начале

2024-02-07 09:18 UTC, McAndyLarkin commented on app/src/main/java/com/example/activities/ActivityA.kt
> +        get() = findViewById<EditText>(R.id.first_name).text.toString()
То есть каждый раз, когда я хочу получить текс вьюхи, мне нужно будет делать дорогую findViewById ?
Это проблема. Пусть результат findViewById будет один раз сохраненн в переменную в onCreate. А потом будем переиспользовать.

2024-02-07 09:18 UTC, McAndyLarkin commented on app/src/main/java/com/example/activities/ActivityA.kt
> +    private fun showNameInToast(button: View) {
button: View никак не используется в этой функции.

2024-02-07 09:19 UTC, McAndyLarkin commented on app/src/main/java/com/example/activities/ActivityA.kt
> +    private fun showNameInToast(button: View) {
И вообще зачем эта функция, если она вызывается однажды, а код в ней небольшой и понятный.

2024-02-07 09:20 UTC, McAndyLarkin commented on app/src/main/java/com/example/activities/ActivityA.kt
>          startActivity(Intent(this, ActivityB::class.java))
Давай переходить по кнопке, а то мгновенный редирект не очень

2024-02-07 10:04 UTC, paxagi commented on app/src/main/java/com/example/activities/ActivityA.kt
> +    private fun showNameInToast(button: View) {
Попросили вынести коллбэк в отдельную функцию в предыдущем PR. 
View пробросил, потому что в функция могла бы использовать его в будущем.

2024-02-07 10:20 UTC, McAndyLarkin commented on app/src/main/java/com/example/activities/ActivityA.kt
> +    private fun showNameInToast(button: View) {
Будущее неопределено,
Будущее в будущем 
![Uploading image.png…]()

2024-02-07 10:21 UTC, McAndyLarkin commented on app/src/main/java/com/example/activities/ActivityA.kt
> +    private fun showNameInToast(button: View) {
Скинь плз ссылку на коммент, где об этом просили
Я посмотрю, в каком контексте

2024-02-07 19:04 UTC, paxagi commented on app/src/main/java/com/example/activities/ActivityA.kt
> +    private fun showNameInToast(button: View) {
> Скинь плз ссылку на коммент, где об этом просили Я посмотрю, в каком контексте

![image](https://github.com/paxagi/Activities/assets/22299289/27d2257b-4d2b-49d9-b70e-8e574ec0ca52)

2024-02-08 15:42 UTC, McAndyLarkin commented on app/src/main/java/com/example/activities/ActivityA.kt
> +    private fun showNameInToast(button: View) {
Нам синке обсудим

2024-02-08 15:43 UTC, McAndyLarkin commented on app/src/main/java/com/example/activities/ActivityA.kt
> +        get() = findViewById<EditText>(R.id.first_name).text.toString()
Не поправлено, но зарезолвлено?

2024-02-08 15:44 UTC, McAndyLarkin requested changes
Ждем правок

2024-02-09 20:23 UTC, MisKuchum approved these changes

2024-02-11 18:15 UTC, McAndyLarkin commented on app/src/main/java/com/example/activities/ActivityB.kt
> +    private val btnNextActivity: Button by lazy {
Поправлять не нужно, но на будущее, отдельные кострукции вокруг инициализации имеет смысл городить, когда есть переиспользование.
А пока они вызываются в одном онКреате можно оставить вызов на месте

2024-02-11 18:17 UTC, McAndyLarkin approved these changes

2024-02-12 09:50 UTC, merged